# Generated by Django 4.2.6 on 2023-10-24 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_benefits"),
    ]

    operations = [
        migrations.AlterField(
            model_name="benefits",
            name="description",
            field=models.TextField(),
        ),
    ]
