# Generated by Django 4.2.7 on 2023-11-11 03:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0008_contactform"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ContactForm",
            new_name="ContactMessage",
        ),
    ]
