# Generated by Django 4.2.7 on 2023-11-11 03:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0009_rename_contactform_contactmessage"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contactmessage",
            old_name="email",
            new_name="email_address",
        ),
    ]
