# Generated by Django 4.2.7 on 2023-11-12 18:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0010_rename_email_contactmessage_email_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactmessage",
            name="country",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
