# Generated by Django 4.2.7 on 2023-11-13 18:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0011_contactmessage_country"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeneralPortfolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="portfolio/imges/")),
                ("url", models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="GrayLiterature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="portfolio/imges/")),
                ("url", models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="InProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="portfolio/imges/")),
                ("url", models.URLField(blank=True)),
            ],
        ),
    ]
